image: python

stages:
  - build
  - test
  # - deploy

variables:
  PLATFORMIO_CACHE_DIR: $CI_PROJECT_DIR/.cache/platformio

before_script:
  - pip install platformio

build:
  stage: build
  script:
    - pio run -e esp32dev --without-uploading
  artifacts:
    paths:
      - .pio/build

test:
  stage: test
  script:
    - pio test -e esp32dev

# deploy:
#   stage: deploy
#   only:
#     - main
#   script:
#     - platformio run --target upload
