image: python

stages:
  # - build
  - test
  # - deploy

variables:
  PLATFORMIO_CACHE_DIR: $CI_PROJECT_DIR/.cache/platformio

before_script:
  - pip install platformio

# build:
#   stage: build
#   script:
#     - platformio run
#   artifacts:
#     paths:
#       - .pio/build

test:
  stage: test
  script:
    - pio run -e firebeetle32

# deploy:
#   stage: deploy
#   only:
#     - main
#   script:
#     - platformio run --target upload
